### ISSUE TITLE
fail compile

### ISSUE THREAD

**Issue by omega-takai** [t--takai/parcel_tutorial#4]
## Written CODE

```scss
header {
  display: block;
  width: 50%;
  background-color: #AAA;
}
.header {
  margin: 0 auto;
}

.main {
  font-size: 40px;
  h1 {
    font-size: 50px;
  }
}
```

but

## Converted CODE
```css
header {
  display: block;
  width: 50%;
  background-color: #AAA; }

._header_1izet_57 {
  margin: 0 auto; }

._main_1izet_60 {
  font-size: 40px; }
  ._main_1izet_60 h1 {
    font-size: 50px; }
```

i don't need `_1izet_57` , `_1izet_60`
